#!/bin/bash

echo "============= MNIST, FC =============" && \
python scope/train.py -v 0 --name test --dataset mnist --fc 20,20 --gradients 1 --epochs 2 --hessian 1 --full_hessian 1 --interpolate_loss 1 --image_resize 0.2 --samples 100 && \
echo "============= CIFAR10, CNN =============" && \
python scope/train.py -v 0 --name test --dataset cifar10 --gradients 1 --epochs 2 --hessian 1 --image_resize 0.5 --samples 100 && \
echo "============= GAUSSIANS =============" && \
python scope/train.py -v 0 --name test --dataset gaussians --fc 20,20 --gradients 1 --epochs 2 --hessian 1 && \
echo "========== DIDN'T CRASH! YEY! ===================="

